# define services: the services that are available for this application
services:
  node-app:
    # node-app service configuration
    container_name: express-node-app-container
    ports:
      - "3000:3000"
    env_file:
      - ./config.env
    # guarantee node app run after mongo is built
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    # annoymuse volume: create place in my directory and store data in it
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./config.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./config.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
  redis:
    image: redis

# volumes: create a named volume for mongo database data, if i need everytime work with same place
volumes:
  mongo-db:
